<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Page Description">
    <meta name="author" content="Pavle Kukic">
    <title>Page Title</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">

</head>
<body>
    <div class="container-fluid" id="navbar-wrapper">
        <ul class="nav navbar-nav text-center" id="navbar">
            <li>
                <a href="#" class="navbar-btn btn-primary">Login</a>
            </li>
            <li>
                <a href="#" class="navbar-btn btn-primary">Register</a>
            </li>
            <li>
                <a href="#" class="navbar-btn btn-primary">Contact</a>
            </li>
            <li class="navbar-brand logo">
                <img src="images/1.png" width="150" height="150">
            </li>
            <li>
                <a href="#" class="navbar-btn btn-primary">Book Now</a>
            </li>
            <li>
                <a href="#" class="navbar-btn btn-primary">Gallery</a>
            </li>
            <li>
                <a href="#" class="navbar-btn btn-primary">About</a>
            </li>

        </ul>

    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
</body>
</html>